from __future__ import annotations

import unittest
from importlib.metadata import version

import unitsentinel


class PackageIdentityTests(unittest.TestCase):
    def test_version_and_public_surface_are_explicit(self) -> None:
        self.assertEqual(unitsentinel.__version__, "0.1.0")
        self.assertEqual(version("unitsentinel"), unitsentinel.__version__)
        self.assertEqual(
            unitsentinel.__all__,
            [
                "AMOUNT_OF_SUBSTANCE",
                "AUTHENTICATION_NOT_PROVIDED",
                "BUILTIN_REGISTRY",
                "COMPARISON_RESULT_SCHEMA",
                "COMPARISON_SCHEMA",
                "COMPARISON_SCOPE_UNDER_PLAN",
                "DIMENSIONLESS",
                "ELECTRIC_CURRENT",
                "LENGTH",
                "LINEAGE_AUTHENTICATION",
                "LUMINOUS_INTENSITY",
                "MASS",
                "MAX_COMPARISON_BINDINGS",
                "NORMALIZATION_EXPRESSION_SCHEMA",
                "NORMALIZATION_LINEAGE_SCHEMA",
                "NORMALIZATION_LINEAGE_SEMANTIC_SCHEMA",
                "NORMALIZATION_SITE_SCHEMA",
                "OUTPUT_NORMALIZATION_SCHEMA",
                "THERMODYNAMIC_TEMPERATURE",
                "TIME",
                "BaseDimension",
                "CertificateDecodeError",
                "CertificateError",
                "CertificateReplay",
                "CertificateReplayError",
                "ComparisonContractError",
                "ComparisonDecodeError",
                "ComparisonError",
                "ComparisonPlan",
                "ComparisonPolicy",
                "ComparisonReason",
                "ComparisonResult",
                "ComparisonResultDecodeError",
                "ComparisonStatus",
                "ComparisonValidationError",
                "ComputationGraph",
                "ConstraintSource",
                "ConstraintWitness",
                "ContractBinding",
                "ContractComparison",
                "ConversionError",
                "Dimension",
                "DimensionError",
                "GraphDecodeError",
                "GraphError",
                "GraphValidationError",
                "InferredContract",
                "InterfaceEndpoint",
                "InterfaceRole",
                "InterfaceSnapshot",
                "LineageError",
                "LineageExpression",
                "LineageSide",
                "MismatchCode",
                "Node",
                "NormalizationLineage",
                "NormalizationSite",
                "Operation",
                "OutputLineage",
                "OutputNormalizationComparison",
                "ProofCertificate",
                "Quantity",
                "QuantityKind",
                "RegistryError",
                "RepairError",
                "RepairLimits",
                "RepairReason",
                "RepairStatus",
                "ReplayReason",
                "ReplayStatus",
                "ScalarType",
                "SolverLimits",
                "Unit",
                "UnitAlias",
                "UnitDefinitionError",
                "UnitRegistry",
                "UnitRepairCandidate",
                "UnitRepairResult",
                "UnitSentinelError",
                "UnknownReason",
                "UnknownUnitError",
                "ValueSpec",
                "VerificationError",
                "VerificationResult",
                "VerificationStatus",
                "__version__",
                "compare_graphs",
                "constraint_catalog",
                "create_certificate",
                "decode_certificate",
                "decode_comparison_plan",
                "decode_comparison_result",
                "decode_graph",
                "encode_certificate",
                "encode_comparison_plan",
                "encode_comparison_result",
                "encode_graph",
                "extract_normalization_lineage",
                "propose_unit_annotation_repair",
                "replay_certificate",
                "verify_graph",
            ],
        )


if __name__ == "__main__":
    unittest.main()
