"""Exact dimensional contracts for scientific and ML computation graphs."""

from typing import Final

from .domain import (
    AMOUNT_OF_SUBSTANCE,
    DIMENSIONLESS,
    ELECTRIC_CURRENT,
    LENGTH,
    LUMINOUS_INTENSITY,
    MASS,
    THERMODYNAMIC_TEMPERATURE,
    TIME,
    BaseDimension,
    ConversionError,
    Dimension,
    DimensionError,
    Quantity,
    QuantityKind,
    Unit,
    UnitDefinitionError,
    UnitSentinelError,
)
from .graph import (
    ComputationGraph,
    GraphError,
    GraphValidationError,
    Node,
    Operation,
    ScalarType,
    ValueSpec,
)
from .graph_codec import GraphDecodeError, decode_graph, encode_graph
from .registry import (
    BUILTIN_REGISTRY,
    RegistryError,
    UnitAlias,
    UnitRegistry,
    UnknownUnitError,
)
from .verification import (
    ConstraintSource,
    ConstraintWitness,
    InferredContract,
    SolverLimits,
    UnknownReason,
    VerificationError,
    VerificationResult,
    VerificationStatus,
)

__version__: Final = "0.1.0"

__all__ = [
    "AMOUNT_OF_SUBSTANCE",
    "BUILTIN_REGISTRY",
    "DIMENSIONLESS",
    "ELECTRIC_CURRENT",
    "LENGTH",
    "LUMINOUS_INTENSITY",
    "MASS",
    "THERMODYNAMIC_TEMPERATURE",
    "TIME",
    "BaseDimension",
    "ComputationGraph",
    "ConstraintSource",
    "ConstraintWitness",
    "ConversionError",
    "Dimension",
    "DimensionError",
    "GraphDecodeError",
    "GraphError",
    "GraphValidationError",
    "InferredContract",
    "Node",
    "Operation",
    "Quantity",
    "QuantityKind",
    "RegistryError",
    "ScalarType",
    "SolverLimits",
    "Unit",
    "UnitAlias",
    "UnitDefinitionError",
    "UnitRegistry",
    "UnitSentinelError",
    "UnknownReason",
    "UnknownUnitError",
    "ValueSpec",
    "VerificationError",
    "VerificationResult",
    "VerificationStatus",
    "__version__",
    "decode_graph",
    "encode_graph",
]
