"""Exact dimensional contracts for scientific and ML computation graphs."""

from typing import Final

from .certificate import (
    CertificateDecodeError,
    CertificateError,
    ProofCertificate,
    create_certificate,
    decode_certificate,
    encode_certificate,
)
from .comparison_codec import (
    ComparisonDecodeError,
    decode_comparison_plan,
    encode_comparison_plan,
)
from .comparison_contract import (
    COMPARISON_SCHEMA,
    MAX_COMPARISON_BINDINGS,
    ComparisonContractError,
    ComparisonPlan,
    ComparisonValidationError,
    ContractBinding,
    InterfaceEndpoint,
    InterfaceRole,
)
from .domain import (
    AMOUNT_OF_SUBSTANCE,
    DIMENSIONLESS,
    ELECTRIC_CURRENT,
    LENGTH,
    LUMINOUS_INTENSITY,
    MASS,
    THERMODYNAMIC_TEMPERATURE,
    TIME,
    BaseDimension,
    ConversionError,
    Dimension,
    DimensionError,
    Quantity,
    QuantityKind,
    Unit,
    UnitDefinitionError,
    UnitSentinelError,
)
from .graph import (
    ComputationGraph,
    GraphError,
    GraphValidationError,
    Node,
    Operation,
    ScalarType,
    ValueSpec,
)
from .graph_codec import GraphDecodeError, decode_graph, encode_graph
from .registry import (
    BUILTIN_REGISTRY,
    RegistryError,
    UnitAlias,
    UnitRegistry,
    UnknownUnitError,
)
from .repair import (
    RepairError,
    RepairLimits,
    RepairReason,
    RepairStatus,
    UnitRepairCandidate,
    UnitRepairResult,
    propose_unit_annotation_repair,
)
from .replay import (
    CertificateReplay,
    CertificateReplayError,
    ReplayReason,
    ReplayStatus,
    replay_certificate,
)
from .verification import (
    ConstraintSource,
    ConstraintWitness,
    InferredContract,
    SolverLimits,
    UnknownReason,
    VerificationError,
    VerificationResult,
    VerificationStatus,
)
from .verifier import constraint_catalog, verify_graph
from .version import VERSION

__version__: Final = VERSION

__all__ = [
    "AMOUNT_OF_SUBSTANCE",
    "BUILTIN_REGISTRY",
    "COMPARISON_SCHEMA",
    "DIMENSIONLESS",
    "ELECTRIC_CURRENT",
    "LENGTH",
    "LUMINOUS_INTENSITY",
    "MASS",
    "MAX_COMPARISON_BINDINGS",
    "THERMODYNAMIC_TEMPERATURE",
    "TIME",
    "BaseDimension",
    "CertificateDecodeError",
    "CertificateError",
    "CertificateReplay",
    "CertificateReplayError",
    "ComparisonContractError",
    "ComparisonDecodeError",
    "ComparisonPlan",
    "ComparisonValidationError",
    "ComputationGraph",
    "ConstraintSource",
    "ConstraintWitness",
    "ContractBinding",
    "ConversionError",
    "Dimension",
    "DimensionError",
    "GraphDecodeError",
    "GraphError",
    "GraphValidationError",
    "InferredContract",
    "InterfaceEndpoint",
    "InterfaceRole",
    "Node",
    "Operation",
    "ProofCertificate",
    "Quantity",
    "QuantityKind",
    "RegistryError",
    "RepairError",
    "RepairLimits",
    "RepairReason",
    "RepairStatus",
    "ReplayReason",
    "ReplayStatus",
    "ScalarType",
    "SolverLimits",
    "Unit",
    "UnitAlias",
    "UnitDefinitionError",
    "UnitRegistry",
    "UnitRepairCandidate",
    "UnitRepairResult",
    "UnitSentinelError",
    "UnknownReason",
    "UnknownUnitError",
    "ValueSpec",
    "VerificationError",
    "VerificationResult",
    "VerificationStatus",
    "__version__",
    "constraint_catalog",
    "create_certificate",
    "decode_certificate",
    "decode_comparison_plan",
    "decode_graph",
    "encode_certificate",
    "encode_comparison_plan",
    "encode_graph",
    "propose_unit_annotation_repair",
    "replay_certificate",
    "verify_graph",
]
